### PR TITLE
Reload no gunshot

### PR DESCRIPTION
**Pull request by Widge-5**
I have noticed when reloading, by shooting off-screen, in the games that support it, the normal gunshot events happen as well as the reloading events.

By that, I mean that you see the muzzle-flash crosshair, hear a gunshot sound and the remaining bullet count drops by one, a fraction of a second before you hear the reload sound and see the bullet count refill.  I assumed this was because the lua script doesn't differentiate between a shot fired onscreen and offscreen when deciding whether to perform the gunshot events.

I found the part in the singe file that executes the gunshot events and added an `and not` condition to the `if` statement using the out-of-bounds values from the reload section.  This seems to have the desired effect of preventing the gunshot events from occurring when an offscreen-reload is intended.

I have only been able to successfully apply the modification to Crime Patrol, Drug Wars, Last Bounty Hunter, and Mad Dog 2.  My knowledge of lua (and of the singe scripting) is minimal at best so I appreciate that my method may have unintended side effects that I have not accounted for.  This PR is meant with the best intentions as information only to raise attention to the issue and a possible solution to be implements at your discretion.

### CODE REVIEW

**Comment by DirtBagXon** [comment]
Hey, @Widge-5 thanks for these. 

I have just tried one out using using mouse on these and what this does do is basically stop you being able to fire a shot within the last 10pixels around the edge of the video area, giving the gun empty sound. This is probably less obvious when using a gun, but a little unusual when using the mouse...

It might be wise to add a VARIABLE at the beginning of the `<game>.singe` file to switch this behaviour back for original _(and/or)_ mouse users:

```
--- a/00-singe2-ports-gungames/crimepatrol-hd/crimepatrol-hd.singe
+++ b/00-singe2-ports-gungames/crimepatrol-hd/crimepatrol-hd.singe
@@ -21,6 +21,8 @@ This file is part of CRIME PATROL (SINGE EDITION)
 
 MYDIR = "singe/crimepatrol-hd/"
 
+GUNEDGE_RELOAD = 0   -- Set to '1' for Gun triggering.
+
 dofile(MYDIR .. "globals.singe")
 dofile(MYDIR .. "setuplevel.singe")
 dofile(MYDIR .. "hscore.singe")
@@ -5229,8 +5231,16 @@ function onInputPressed(intWhat)
                if (intWhat == SWITCH_BUTTON3) then
 
                        p1BUTTON3 = true
+                       GUN_EDGE = true
 
-                       if (iBullets > 0) then
+                       if (GUNEDGE_RELOAD == 1) then 
+
+                               if ((mousex <= 10 or mousex >= resX-10) or (mousey <= 10 or mousey >= resY-10)) then
+                                       GUN_EDGE = false
+                               end
+                       end
+
+                       if (iBullets > 0 and GUN_EDGE) then
 
                                if bAmmo then
```

**Comment by Widge-5** [comment]
Thank you @DirtBagXon for taking the time to look.

This is very interesting to me, I've not explored these scripts before and I'm fascinated by what has been achieved.  you've done some great work.

I only copied the condition from the section of code that dictates at what distance from the edge the reload occurs.  Your original code (line 5366 of `crimepatrol-hd.singe` has a reload triggered within 10px of the edge and without my edit to disable the gunshot at the same distance, both a reload and gunshot occur simultaneously within that range for lightgun and mouse users, which is possibly just as bad as a no-shot being registered within the space.

I assumed the generous 10px was for the benefit of mouse users but removing the +/- 10px entirely from both gunshot and reload tests would be absolutely fine for a lightgun user and possibly a mouse user too?

Although I do find that there's still quite a large area on the *right* edge where no shot is registered so there may be another line somewhere reducing the functional area of the mouse/gun.  This can be overcome by making the condition for the right edge `mousex >= resX+40` although I appreciate that is less than an ideal solution to that particular problem.


So my suggestion becomes to apply this `if` test to the gunshot event on line 5233:

```if (iBullets > 0) and not ( (mousex <= 0 or mousex >= resX+40) or (mousey <= 0 or mousey >= resY) ) then```

and this `if` test to the reload event on line 5366: 

```if (mousex <= 0 or mousex >= resX+40) or (mousey <= 0 or mousey >= resY) then```

(line numbers relate to `crimepatrol-hd.singe`, they may differ for the other games)

This allows gunshots to fire across the full area of the screen, and only triggers offscreen reloading on the very edges with no overlap and no "dead" zone.

I tested briefly with a lightgun and a touchpad and both seem to behave as I expect. The touchpad/mouse is still able to reload offscreen by clicking on the very edges. The accuracy of the shots appeared to be unaffected.

**Comment by DirtBagXon** [comment]
_"you've done some great work"_ - Oh please don't give me credit here, this is all the game devs (_RDG, Karis_) not me. I just adapt.

Each of these "_gun games_" have an individual codebase, so it's not surprising you are seeing differences in each game. Probably written over different timespans, mostly over a decade ago, and improvements added.

I'll try the suggested changes shortly, but the logic seems sound.

**Comment by DirtBagXon** [comment]
The changes above still affect mouse style play in an impact-full way, I think these are just different use cases. Singe games were written for mouse originally so I guess that's the coded experience. 

Can you try these changes in `crimepatrol-hd.singe`, as this seems to restore mouse behaviour:

```
--- a/00-singe2-ports-gungames/crimepatrol-hd/crimepatrol-hd.singe
+++ b/00-singe2-ports-gungames/crimepatrol-hd/crimepatrol-hd.singe
@@ -5230,7 +5230,7 @@ function onInputPressed(intWhat)
 
                        p1BUTTON3 = true
 
-                       if (iBullets > 0) then
+                       if (iBullets > 0) and not ( (mousex < 0 or mousex > resX+40) or (mousey < 0 or mousey > resY) ) then
 
                                if bAmmo then
 
@@ -5363,7 +5363,7 @@ function onInputReleased(intWhat)
                                        
                                elseif(dip_ReloadTrigger == DOPT_BORDERS) then
                                
-                                       if (mousex <= 10 or mousex >= resX-10) or (mousey <= 10 or mousey >= resY-10) then
+                                       if (mousex < 10 or mousex >= resX+40) or (mousey <= 0 or mousey >= resY) then
 
                                                if (iBullets <= dip_MaxBullets) then    -- Reload is there is less than max (avoid emptying bonus bullets)
                                                        relIndex = iBullets
```

Still not certain why the `+40` - but it doesn't seem to affect behaviour on my testing.

**Comment by Widge-5** [comment]
Using what you've  provided recreates the original behaviour whereby offscreen reloading causes a gunshot event at the same time as a reload event (the values tested for in the gunshot test are all outside of the area that can reached, so there's no place where a gunshot will not be fired).  In order to prevent overlap, the values of the two `if` tests need to be identical.

What is the impact on mouse use?  Perhaps it would help if I understood what the ideal behaviour for a mouse user would be.
For a lightgun user, the most ideal situation would be to have the full screen area available for gunfire minus only the outer edges for reload, so that aiming and shooting off the edge of the screen registers as a click _on_ the edge triggering a reload _only_ - (so just 1px around the edge for the reload-zone everything else for shooting with no overlap) which I think is what I achieved with the suggestion in my last comment.

If it's ideal for a mouse user to have the overlap and/or an unshootable wide area around the near-edges as a "reload zone" then perhaps I can add another reload option to the service menu so that the original behaviour is preserved but if, say, a "Lightgun" reload option is selected then the alternate behaviour is used instead.  - similar to your original response, suggesting a variable to switch behaviour, but accessible from the game service menu.

**Comment by Widge-5** [comment]
As an example, I've added that option in to crimepatrol-hd (3 files changed).  All the original reload options are in place with the original behaviour, and an additional reload option called "Lightgun" is now accessible which gives the behaviour I suggested. I hope this is ok, I don't want to do anything that you're not happy to include.  If you think it's a good addition then I can look at making the same change to the other games. But I will spend some time testing this on CP-HD to make sure there's no side-effect

**Comment by DirtBagXon** [comment]
Tested the `crimepatrol-hd` changes and all looks good.

**Comment by Widge-5** [comment]
Just a little cleanup on `crimepatrol-hd.singe`, stopped an attempted offscreen reload if bullets already at max.

**Comment by Widge-5** [comment]
Sorry.  I accidentally closed the PR when I renamed the branch. Didn't realise that would happen.

**Comment by Widge-5** [comment]
- Trigger Activated crosshair option now has an animated gunshot/muzzle-flash instead of a static image.  WSJR Noir also shows the animated muzzle flash on all crosshair options as this was the previous behaviour with the static one; but not WSJR SD or HD.
- Trigger Activated crosshair option for some SD games corrected to show the flash instead of a gun icon.
- Trigger Activated crosshair no-longer follows the mouse. It shows only at the spot where the shot was fired.
- New reload option, "Lightgun" added to all shooting games where reloading is a thing. This makes the full screen area shootable,  with offscreen reloading possible when shooting outside of the screen area and no overlap between shooting and reloading zones; And secondary-button-activated reloading possible at all times when bullets are not full.  The behaviour of the pre-existing reload options is unchanged.
- Improved crosshair/aim alignment for lightgun users (I hope).
Freedom Fighter is the only shooting game not changed.

**Comment by DirtBagXon** [comment]
A few `.commands` files from the RetroPie install have crept in.

Could you remove them please :)

**Comment by Widge-5** [comment]
Thanks. Yes, three crept in.  They've now been removed.

**Comment by Widge-5** [comment]
Fixed the "High Score Bug" whereby the game would crash if no name was entered on the high-score name-entry screen for some games.  Only for shooting games, it may still exist on some other games.
Added handling for the new -xaxis and -yaxis command switches for all of the shooting games.

**Pull request merged**
